[tool.ruff]
select = ["B", "B9", "C", "D", "DAR", "E", "F", "N", "RST", "S", "W"]
ignore = ["E203", "E501", "RST201", "RST203", "RST301", "W503", "D100", "D103", "N802", "C901", "D205", "D212", "D415", "N803", "B950", "B008"]
line-length = 80

exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
]

[tool.ruff.mccabe]
max-complexity = 10